<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <RootNamespace>SPQR.DbCheck</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SPQR.Core\SPQR.Core.csproj" />
    <ProjectReference Include="..\..\src\SPQR.Persistence\SPQR.Persistence.csproj" />
  </ItemGroup>
</Project>
